# Generated by Django 3.1.4 on 2021-03-13 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('department_desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='RaisedIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('incident_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=50)),
                ('incident_type', models.CharField(max_length=250)),
                ('incident_status', models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], max_length=50)),
                ('created_date', models.DateTimeField()),
                ('resolution_date', models.DateTimeField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('incident_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=50)),
                ('incident_status', models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], max_length=50)),
                ('created_date', models.DateTimeField()),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.criticalservice')),
            ],
        ),
        migrations.CreateModel(
            name='ClosedIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('incident_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=50)),
                ('incident_type', models.CharField(max_length=250)),
                ('incident_status', models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], max_length=50)),
                ('created_date', models.DateTimeField()),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='BacklogIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('incident_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=50)),
                ('incident_type', models.CharField(max_length=250)),
                ('incident_status', models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], max_length=50)),
                ('created_date', models.DateTimeField()),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
    ]
