# Generated by Django 3.1.4 on 2021-03-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_backlogincident_closedincident_criticalincident_criticalservice_department_raisedincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogincident',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raisedincident',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raisedincident',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
